packageNum: 632
packageIdent: knb-lter-cap.632.9
title: "Desert Fertilization Experiment: investigation of Sonoran desert ecosystem response to atmospheric deposition and experimental nutrient addition, ongoing since 2006"
geographicCoverage:
  geographicDescription: 'CAP LTER study area: greater Phoenix, Arizona (USA) metropolitan
    area and surrounding Sonoran desert region'
